### PR TITLE
fix admin checkings and weapon blacklist fix

### PR DESCRIPTION
**Pull request by CsokiHUN**
Only one admin had a rank because the for loop was faulty.

### CODE REVIEW

**Comment by CsokiHUN** [comment]
In my version, it doesn't delete all the guns except the one on the blacklist.

**Comment by AmIrReZa386** [comment]
Hi @CsokiHUN,

Thanks for your pull request .
We are test this code & don't have any problem .

for example :
```
RemoveAllPedWeapons(PlayerPedId(), true)
``` 
This true you can check https://docs.fivem.net/natives/?_0xF25DF915FA38C5F3 from FiveM document !

if i put `RemoveWeaponFromPed` player (maybe cheater) ram involved for find that weapon .

About admin system `'` there is no difference with `"` this is because of `for ... do` problem i will fix it soon !

**Comment by CsokiHUN** [comment]
I rewrote the weapon removal so that it does not only remove the weapon on the blacklist. By default, it removes all of them.

I fixed the admin check merge is available.

```
About admin system ' there is no difference with " this is because of for ... do problem i will fix it soon !
```
I know there is no difference, I just used a formatter and it rewrote it.

**Comment by AmIrReZa386** [comment]
okey i accept your **Merge pull request** thanks for choose my anti cheat !

**Pull request merged**
